name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜运行
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync upstream
        uses: aormsby/fork-sync-with-upstream-action@v3.2
        with:
          upstream_repository: lilingfengdev/deepapi
          upstream_branch: main
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}